idp.authn.LDAP.ldapURL = ldap://op1-ldap:389
idp.authn.LDAP.authenticator = bindSearchAuthenticator
idp.authn.LDAP.useStartTLS = false
idp.authn.LDAP.useSSL = false
idp.authn.LDAP.baseDN = ou=people,dc=op1,dc=dev,dc=localhost
idp.authn.LDAP.bindDN = cn=admin,dc=op1,dc=dev,dc=localhost
idp.authn.LDAP.bindDNCredential = adminpw
idp.authn.LDAP.userFilter = (uid={user})
idp.authn.LDAP.dnFormat = uid=%s,ou=people,dc=op1,dc=dev,dc=localhost
idp.authn.LDAP.returnAttributes = businessCategory carLicense cn departmentNumber description displayName employeeNumber employeeType facsimileTelephoneNumber givenName initials l mail manager mobile o ou physicalDeliveryOfficeName postOfficeBox postalAddress postalCode preferredLanguage seeAlso sn st street telephoneNumber title uid
