ServerName https://sp1.dev.localhost
SetEnvIf X-Forwarded-Proto "^https$" HTTPS=on

<VirtualHost *:80>
    ServerName https://sp1.dev.localhost
    UseCanonicalName On

    DocumentRoot /var/www/html
    DirectoryIndex index.html

    MellonCacheSize 100
    MellonLockFile /var/run/apache2/mellon.lock

    <Location />
        AuthType Mellon
        MellonEnable auth
        MellonEndpointPath /mellon
        MellonSPPrivateKeyFile /etc/apache2/mellon/sp.key
        MellonSPCertFile /etc/apache2/mellon/sp.crt
        MellonSPMetadataFile /etc/apache2/mellon/mdq-sp1.xml
        MellonIdPMetadataFile /etc/apache2/mellon/idp.xml
        MellonDiscoveryURL https://ds.dev.localhost/
        MellonSecureCookie On
        Require valid-user
    </Location>

    <Location /mellon>
        AuthType Mellon
        MellonEnable info
        MellonEndpointPath /mellon
        MellonSPPrivateKeyFile /etc/apache2/mellon/sp.key
        MellonSPCertFile /etc/apache2/mellon/sp.crt
        MellonSPMetadataFile /etc/apache2/mellon/mdq-sp1.xml
        MellonIdPMetadataFile /etc/apache2/mellon/idp.xml
        MellonDiscoveryURL https://ds.dev.localhost/
        MellonSecureCookie On
        Require all granted
    </Location>

    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
    <Directory /usr/lib/cgi-bin>
        Options +ExecCGI
        AddHandler cgi-script .cgi
        Require all granted
    </Directory>
</VirtualHost>

