services:
  offa:
    image: oidfed/offa:0.4.2
    restart: unless-stopped
    volumes:
      - ./offa/config.yaml:/config.yaml:ro
      - ./offa/data:/data
      - ../caddy/data/caddy/pki/authorities/local/root.crt:/usr/local/share/ca-certificates/caddy-local-root.crt:ro
    networks:
      caddy:
        aliases:
          - rp1.dev.localhost
          - rp1.dev.internal

  # This would be your service
  whoami:
    image: containous/whoami
    restart: unless-stopped
    networks:
      caddy:
        aliases:
          - whoami.dev.localhost
          - whoami.dev.internal

networks:
  caddy:
    external: true
    name: caddy-network
