services:
  mdq:
    image: edugain-pilot/mdq:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./metadata:/metadata:ro
    networks:
      caddy:
        aliases:
          - mdq.dev.localhost
          - mdq.dev.internal

networks:
  caddy:
    external: true
    name: caddy-network

