server:

logging:
  access:
    level: debug
    stderr: true
  internal:
    level: debug
    stderr: true

sessions:
  ttl: 3600
  cookie_domain: .dev.localhost

auth:
    - domain: whoami.dev.localhost

federation:
  entity_id: https://rp1.dev.localhost
  trust_anchors:
    - entity_id: https://ta.dev.localhost
    - entity_id: https://ia1.dev.localhost
  authority_hints:
    - https://ia1.dev.localhost
  organization_name: "eduGAIN"
  use_resolve_endpoint: true

op_discovery:
  local:
    use_entity_collection_endpoint: true

signing:
  key_storage: /data/signing

debug_auth: true

