server:

logging:
  access:
    level: debug
    stderr: true
  internal:
    level: debug
    stderr: true

sessions:
  ttl: 3600
  cookie_domain: oidf-pilot.edugain.org

auth:
    - domain: whoami.oidf-pilot.edugain.org

federation:
  entity_id: https://rp1.oidf-pilot.edugain.org
  trust_anchors:
    - entity_id: https://ta.oidf-pilot.edugain.org
    - entity_id: https://ia1.oidf-pilot.edugain.org
  authority_hints:
    - https://ia1.oidf-pilot.edugain.org
  organization_name: "eduGAIN"
  use_resolve_endpoint: true

op_discovery:
  local:
    use_entity_collection_endpoint: true

signing:
  key_storage: /data/signing

debug_auth: true

